### PR TITLE
new endpoint created - getUserPublicInfo; retrieves all public information about a user from user_info property object

### PR DESCRIPTION
**Pull request by kristijanH1998**
Frontend will need user's public information such as biography, first name, profile picture, etc., and for profile picture base64 format is required to be able to convert it to actual image format (png, jpg etc.)

### CODE REVIEW

**Comment by JJeshua** [comment]
I'm curious what the intended use of this endpoint is? We are already returning the user info (including the profile picture) in all the endpoints that fetch the users, like getComments and getLikes.

I think you should change this endpoint to something like /user/profile/:username and return all of their information that should be public like their username, profile image, and biography. We will need something like this when a user is on the feed page and wants to click into a users profile which will need to render all that public information: username, profile picture, biography, etc.

**Comment by kristijanH1998** [comment]
Code edited to return all user's personal information from user_info property, including base64 profile image.

**Review by vlomeli — APPROVED** [review]
Works on my end

**Review by vlomeli — APPROVED** [review]
lgtm

**Review by JJeshua — APPROVED** [review]
LGTM. Added these new tests to our testing tool.

**Pull request merged**
