### PR TITLE
refactored getReactionAndUserData to fetch base64 image for getCommsF…

### PR DESCRIPTION
**Pull request by kristijanH1998**
refactored getReactionAndUserData to fetch base64 image for getCommsForPost and getLikesForPost endpoints, and changed code of getProfile controller to return user account data with base64 image instead of Buffer

### CODE REVIEW

**Comment by JJeshua** [comment]
Screenshot 2024-05-18 213355

These tests fail. Not sure if we need to refactor the tests or if the changes in the pull request are causing them to fail (we can ignore the public info tests failing since this pull request is behind).

**Review by Ephraim-Winston — APPROVED** [review]

**Comment by kristijanH1998** [comment]
> Screenshot 2024-05-18 213355
> 
> These tests fail. Not sure if we need to refactor the tests or if the changes in the pull request are causing them to fail (we can ignore the public info tests failing since this pull request is behind).

Changes made to address these errors, needs further review and approval

**Review by vlomeli — APPROVED** [review]
works for me

**Review by JJeshua — APPROVED** [review]
LGTM.

**Pull request merged**
