### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by JJeshua**
Normalizes line endings to use LF instead of CRLF.

Fixes issues when different OS's format line endings differently. LF will work on all OS's, whereas CRLF (windows's line feed) will not.

image

### CODE REVIEW

**Comment by kristijanH1998** [comment]
I tried testing this with this branch running on backend and 'main' branch active on Python automated testing tool, and more than half of the tests fail. To make sure that main on backend works, I test ran the Python tool again but with 'main' on backend and all tests succeed. So I assume that this branch needs to be merged with main locally with 'git merge main' and those changes pushed to it, then it will be in sync with main and all tests should succeed. The tests screenshot is attached.
errors

**Review by kristijanH1998 — APPROVED** [review]
just needs to be synced with main

**Review by kristijanH1998 — APPROVED** [review]
lgtm

**Review by vlomeli — APPROVED** [review]
LGTM

**Pull request merged**
