### PR TITLE
Archive post feature ready

### PR DESCRIPTION
**Pull request by JJeshua**

### CODE REVIEW

**Review by A13xYanez — APPROVED** [review]
Code has been tested and is functional. Updates the post "post_is_archived" from false to true as intended.

**Review by vlomeli — APPROVED** [review]
works on my setup as intended

**Comment by vlomeli** [comment]
when I open it on my machine and test with an id from one of my posts i get 200 ok response

**Review by A13xYanez — APPROVED** [review]
All is good

**Pull request merged**
